# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fft_arma <- function(y_) {
    .Call(`_MLvdm_fft_arma`, y_)
}

ifft_arma <- function(y_) {
    .Call(`_MLvdm_ifft_arma`, y_)
}

rcpparma_hello_world <- function() {
    .Call(`_MLvdm_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_MLvdm_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_MLvdm_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_MLvdm_rcpparma_bothproducts`, x)
}

tmp_dot_prod <- function(x, y) {
    .Call(`_MLvdm_tmp_dot_prod`, x, y)
}

complex_dot_prod <- function(x, y) {
    .Call(`_MLvdm_complex_dot_prod`, x, y)
}

complex_rowsum <- function(x) {
    .Call(`_MLvdm_complex_rowsum`, x)
}

complex_rowsum_matrix <- function(x) {
    .Call(`_MLvdm_complex_rowsum_matrix`, x)
}

complex_abs <- function(x) {
    .Call(`_MLvdm_complex_abs`, x)
}

get_real <- function(x) {
    .Call(`_MLvdm_get_real`, x)
}

get_im <- function(x) {
    .Call(`_MLvdm_get_im`, x)
}

assign_im <- function(x, new_im) {
    .Call(`_MLvdm_assign_im`, x, new_im)
}

assign_re <- function(x, new_re) {
    .Call(`_MLvdm_assign_re`, x, new_re)
}

add_re <- function(x, new_re) {
    invisible(.Call(`_MLvdm_add_re`, x, new_re))
}

sub_re <- function(x, new_re) {
    invisible(.Call(`_MLvdm_sub_re`, x, new_re))
}

mul_re <- function(x, new_re) {
    invisible(.Call(`_MLvdm_mul_re`, x, new_re))
}

div_re <- function(x, new_re) {
    invisible(.Call(`_MLvdm_div_re`, x, new_re))
}

div_vector <- function(x, new_) {
    invisible(.Call(`_MLvdm_div_vector`, x, new_))
}

div_scalar <- function(x, scal) {
    invisible(.Call(`_MLvdm_div_scalar`, x, scal))
}

mul_scalar <- function(x, scal) {
    invisible(.Call(`_MLvdm_mul_scalar`, x, scal))
}

add_im <- function(x, new_im) {
    invisible(.Call(`_MLvdm_add_im`, x, new_im))
}

fftshift_num <- function(x, inverse = FALSE) {
    .Call(`_MLvdm_fftshift_num`, x, inverse)
}

fftshift_com <- function(x, inverse = FALSE) {
    .Call(`_MLvdm_fftshift_com`, x, inverse)
}

vmd <- function(signal, tau = 0, alpha = 2000L, K = 3L, tol = 0.00001, N = 500L, init = 0L, DC = TRUE) {
    .Call(`_MLvdm_vmd`, signal, tau, alpha, K, tol, N, init, DC)
}

